apiVersion: v1
kind: Service
metadata:
  name: msvc-integrator-service
spec:
  selector:
    app: msvc-integrator-service
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort

# esta parte es de GCP para crear el ingress asi bien bacano :)
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: msvc-integrator-service-ingress
#  annotations:
#    kubernetes.io/ingress.class: "gce"  # Usa el controlador de GCP
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: msvc-integrator-service
#            port:
#              number: 80
