apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        ports:
        - containerPort: 5672
          name: amqp
        - containerPort: 15672
          name: management
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "1.5Gi"
            cpu: "1800m"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-integrator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-integrator-service
  template:
    metadata:
      labels:
        app: msvc-integrator-service
    spec:
      containers:
      - name: msvc-integrator-service
        image: msvc-integrator-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: QUEUE_NAME
          value: "message_queue"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-integrator-service
spec:
  selector:
    app: msvc-integrator-service
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-medical-record
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-medical-record
  template:
    metadata:
      labels:
        app: msvc-medical-record
    spec:
      containers:
      - name: msvc-medical-record
        image: msvc-medical-record:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: QUEUE_NAME
          value: "message_queue"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-medical-record
spec:
  selector:
    app: msvc-medical-record
  ports:
  - port: 80
    targetPort: 5000
  type: NodePort